name: braking
channels:
  - pytorch
  - nvidia
  - pytorch3d
dependencies:
  - python=3.10
  - pytorch-cuda=11.8
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - pytorch3d
  - conda-forge::mpi4py
  - conda-forge::openmpi
