path_to_exp_dir: ../data/ITS/kyushu_driving_database/experiments
path_to_db: ../data/ITS/kyushu_driving_database/databases/cleaned/probe_data_annotated_distance.db
columns: ["datetime", "speed", "accel_x", "accel_y", "accel_z", "accel", "latitude", "longitude", "direction"]
offset: 4
