path_to_db: /home/user/data/ITS/kyushu_driving_database/databases/cleaned/probe_data_annotated_distance.db
detector:
  method: gbdt
  gt_flags: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
  offset: 4
  columns: ["datetime", "speed", "accel_x", "accel_y", "accel_z", "accel", "latitude", "longitude", "direction"]
  test_size: 0.2
  depth: 10
  n_iters: 10000
  lr: 0.001
  early_stopping_rounds: 1000
  random_state: 233
  verbose: true
